language: java
sudo: false

before_install:
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
  - chmod +x gradlew

script:
  - ./gradlew mmupnp:check
  - ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false

branches:
  except:
    - gh-pages
